/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package olympic;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class Sports extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;

    /**
     * Creates new form Sports
     */
    public Sports() {
        initComponents();
         conn=javaconnect.ConnectDb();
          Toolkit toolkit = getToolkit();
          Dimension size = toolkit.getScreenSize();
          setLocation(size.width/2 - getWidth()/2,
          size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_height = new javax.swing.JTextField();
        txt_weight = new javax.swing.JTextField();
        txt_div = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        cob1 = new javax.swing.JComboBox();
        btnclear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 102, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("ATHELETE ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 100, 170, 30);

        jLabel3.setBackground(new java.awt.Color(255, 102, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("NAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 190, 80, 30);

        jLabel4.setBackground(new java.awt.Color(255, 102, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("SPORT");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 270, 90, 30);

        jLabel5.setBackground(new java.awt.Color(255, 102, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("HEIGHT");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(820, 90, 110, 30);

        jLabel6.setBackground(new java.awt.Color(255, 102, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("WEIGHT");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(820, 180, 110, 30);

        jLabel7.setBackground(new java.awt.Color(255, 102, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("DIVISION");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(820, 260, 130, 30);

        txt_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_id.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(txt_id);
        txt_id.setBounds(380, 100, 170, 40);

        txt_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txt_name);
        txt_name.setBounds(380, 180, 170, 40);

        txt_height.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_heightActionPerformed(evt);
            }
        });
        jPanel1.add(txt_height);
        txt_height.setBounds(980, 90, 150, 40);

        txt_weight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_weightActionPerformed(evt);
            }
        });
        jPanel1.add(txt_weight);
        txt_weight.setBounds(980, 170, 150, 40);

        txt_div.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_divActionPerformed(evt);
            }
        });
        jPanel1.add(txt_div);
        txt_div.setBounds(980, 260, 150, 40);

        btnadd.setBackground(new java.awt.Color(204, 0, 0));
        btnadd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnadd.setText("ADD");
        btnadd.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd);
        btnadd.setBounds(290, 620, 140, 50);

        btndelete.setBackground(new java.awt.Color(204, 0, 0));
        btndelete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete);
        btndelete.setBounds(460, 620, 140, 50);

        btn_update.setBackground(new java.awt.Color(204, 0, 0));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update);
        btn_update.setBounds(620, 620, 140, 50);

        btnback.setBackground(new java.awt.Color(204, 0, 0));
        btnback.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback);
        btnback.setBounds(950, 620, 140, 50);

        cob1.setBackground(new java.awt.Color(51, 255, 51));
        cob1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cob1.setForeground(new java.awt.Color(0, 0, 102));
        cob1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RUNNING", "WRESTLING", "VOLLEYBALL", "JAVALLIN THROW", "SHOT PUT", "WEIGHT LIFTING", "SHOOTING", "TABLE TENNIS", "FENCING", "SWIMMING", "BADMINTON", "TAEKWONDO", "CYCLING", "TABLE TENNIS", "TENNIS" }));
        cob1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cob1ActionPerformed(evt);
            }
        });
        jPanel1.add(cob1);
        cob1.setBounds(380, 260, 170, 40);

        btnclear.setBackground(new java.awt.Color(240, 0, 0));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear);
        btnclear.setBounds(780, 620, 140, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("SEARCH");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(550, 20, 110, 29);

        txt_search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search);
        txt_search.setBounds(700, 20, 200, 40);

        jLabel1.setNextFocusableComponent(jLabel1);
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 0, 0, 0);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/olympic/images/athlete4.jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 1920, 1200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1604, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1620, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_divActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_divActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
         try{
            String sql="insert into Sports "
                    + "(id,name,sport,"
                    + "height,weight,division) values (?,?,?,?,?,?)";
                   
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_id.getText());
            pst.setString(2,txt_name.getText());
            pst.setString(3, (String) cob1.getSelectedItem());
            pst.setString(4,txt_height.getText());
            pst.setString(5,txt_weight.getText());
            pst.setString(6,txt_div.getText());
          
          
            
            
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data is saved successfully");
            
            
                    
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        finally {
             try{
                 rs.close();
                 pst.close();
             }
             catch(Exception e)
             {
                 JOptionPane.showMessageDialog(null,e);
             }
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
      try{
       String val = txt_name.getText();
         String val2 = (String) cob1.getSelectedItem();
           String val3 = txt_height.getText();
             String val4 =txt_id.getText();
               String val5 = txt_weight.getText();
                 String val6 = txt_div.getText();
                   
                       
   String sql = "update Staff_information2 set id='"+val4+"',name='"+val+"',sport='"+val2+"', height ='"+val3+"',weight = '"+val5+"',division = '"+val6+"' where id='"+val4+"'";
   pst=conn.prepareStatement(sql);
   pst.execute();
   JOptionPane.showMessageDialog(null,"Details Updated");
       
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(null,e);
    }
  finally{
      try{
          
      }catch(Exception e)
      {
          
      }
  }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
            try{
      String sql= " delete from Sports where id=? ";
      pst = conn.prepareStatement(sql);
      pst.setString(1,txt_id.getText());
      pst.execute();
      
      JOptionPane.showMessageDialog(null,"Details Deleted");
      
  }
  catch(Exception e)
    {
        JOptionPane.showMessageDialog(null,e);
    }
  finally{
      try{
          rs.close();
          pst.close();
      }catch(Exception e)
      {
          
      }
  }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void cob1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cob1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cob1ActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        setVisible(false);
       Loading ob=new Loading();
       ob.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void txt_weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_weightActionPerformed

    private void txt_heightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_heightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_heightActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txt_id.setText("");
        txt_name.setText("");
       
        txt_height.setText("");
        txt_weight.setText("");
        txt_div.setText("");
       
       
    }//GEN-LAST:event_btnclearActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
         try{
           
           String sql= "select * from Sports where id=? ";
           
           pst=conn.prepareStatement(sql);
           pst.setString(1,txt_search.getText());
           rs=pst.executeQuery();
           
           String add1=rs.getString("id");
           txt_id.setText(add1);
           
           String add2=rs.getString("name");
         txt_name.setText(add2);
         
         String add3=rs.getString("sport");
       cob1.setSelectedItem(evt);
         
         String add4=rs.getString("height");
         txt_height.setText(add4);
         
         String add5=rs.getString("weight");
         txt_weight.setText(add5);
         
         String add6=rs.getString("division");
         txt_div.setText(add6);
         
         
       //  String add10=rs.getString("Gender");
         //txt_gender.setText(add10);
        // 
       
             }
       catch(Exception e)
       {
           
       }
       finally{
           try{
              rs.close();
              pst.close();
           }catch(Exception e)
           {
               
           }
       }
    }                                      

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {                                          

    }//GEN-LAST:event_txt_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JComboBox cob1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_div;
    private javax.swing.JTextField txt_height;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_weight;
    // End of variables declaration//GEN-END:variables
}
